### ISSUE TITLE
Feature Request: Support PSR-2 coding standard for opening brace following argument definition

### ISSUE THREAD

**Issue by jessarcher** [FooSoft/vim-argwrap#19]
In the PSR-2 coding standard for PHP (and perhaps other coding standards), the position of the opening brace of a method body changes depending on whether the method arguments are single line or multi-line. E.g.

```php
function myFunction($arg1, $arg2, $arg3)
{
   // ...
}
```

```php
function myFunction(
    $arg1,
    $arg2,
    $arg3
) {
    // ...
}
```

When toggling with vim-argwrap, the opening brace is not touched, so toggling between single and multi-line takes extra steps to fix the positioning.

It would be great if there were an option that could be enabled that would automatically handle this.

Thanks for the great plugin!

**Comment by camilledejoye** [comment]
This issue can now be closed #23
