### ISSUE TITLE
[Feature request] support the repeat operator

### ISSUE THREAD

**Issue by voldikss** [FooSoft/vim-argwrap#20]
Thanks for your implementation! This plugin is really helpful.

It will be better of this plugin to support repeat operator provided by [vim-repeat](https://github.com/tpope/vim-repeat).

And I found that vim-gitgutter [implements](https://github.com/airblade/vim-gitgutter/blob/8a4b9ccf529db77fa36e5a2308d53783fd70e362/autoload/gitgutter/hunk.vim#L174) it. How do think about this feature?

**Comment by camilledejoye** [comment]
This issue can now be closed with #22 being merged

**Comment by voldikss** [comment]
Awesome work @elythyr :+1:
