### ISSUE TITLE
Does not work when the cursor is on the opening bracket

### ISSUE THREAD

**Issue by s3rvac** [FooSoft/vim-argwrap#3]
Consider the following line:

```
[1, 2, 3]
```

When I have the cursor inside the brackets or on the closing bracket

```
[1, 2, 3]
        ^
```

the plugin works correctly:

```
[
    1,
    2,
    3
]
```

However, when I have the cursor on the opening bracket

```
[1, 2, 3]
^
```

the plugin does nothing. Would it be possible to make the plugin work also when the cursor is on the opening bracket?

Thanks for a very handy plugin BTW!

**Comment by FooSoft** [comment]
Thanks for the report. I've been aware of this issue for a little while now, and the main culprit is the VIM `searchpairpos` function. It finds a matching set a of braces that surround your current cursor position, and I use this to determine the wrapping "scope". Unfortunately, this does not work (technically speaking it would match the outer brace scope, if there is one) properly when the cursor is on the opening brace. When I get a bit of time, I'll see about getting some workaround in place.
