### ISSUE TITLE
Different rules for different type of braces

### ISSUE THREAD

**Issue by Drachenfels** [FooSoft/vim-argwrap#6]
Plugin is awesome and it works like a charm, however there is one small tweak that probably could make it even more awesome.

If we have this option on:

```
argwrap_tail_comma=1
```

We expect braces {} to be like that:

```
{
    'a',
    'b',
    'c',
}
```

We expect braces [] to be like that:

```
[
    'a',
    'b',
    'c',
]
```

But braces (), to be like that:

```
(
    'a',
    'b',
    'c'
)
```

Why?

In python we don't want to generally have this kind of definitions:

```
def some_function(
    a,
    b,
    c,
)
```

While it's not syntax and pep8/pylint don't complan about it either it's not widespread used coding standard. I imagine some other languages might be more strict about it.

So I would propose to allow define variable like that:

```
argwrap_tail_comma={,(,[
```

To maintain backward compatibility 1 means all types of brackets and 0 none.

**Comment by FooSoft** [comment]
Fixed
